"""Add user confirmation field

Revision ID: 06422d2e403e
Revises: b196ac1963be
Create Date: 2016-03-26 13:13:01.790560

"""

# revision identifiers, used by Alembic.
revision = '06422d2e403e'
down_revision = 'b196ac1963be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
